--1
SELECT DEPARTMENT_NAME AS "학과명" , CATEGORY AS "계영"
FROM tb_department;

--2
SELECT DEPARTMENT_NAME || '의 정원은 '|| CAPACITY || '명 입니다.'
FROM TB_DEPARTMENT; 

--3
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN,8,1) = '2' OR SUBSTR(STUDENT_SSN,8,1) = '4';

SELECT STUDENT_NAME, DEPARTMENT_NAME, STUDENT_SSN
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE (SUBSTR(STUDENT_SSN,8,1) = '2' OR SUBSTR(STUDENT_SSN,8,1) = '4')
        AND DEPARTMENT_NAME LIKE '%국문%';
        
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE (SUBSTR(STUDENT_SSN,8,1) = '2' OR SUBSTR(STUDENT_SSN,8,1) = '4')
        AND DEPARTMENT_NAME LIKE '%국문%';

--4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

-- 5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT DEPARTMENT_NO
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT DISTINCT  CLASS_NO
FROM TB_GRADE
JOIN TB_CLASS USING( CLASS_NO)
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE,1,2 )='02';

